export const generateTimeSlots = () => {
  const ruang2_1 = {
    "2024-10-09": [
      {
        time: "08:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "08:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "09:00",
        status: "booked",
        room: "Ruang 2.1",
        borrower: "John Doe",
        role: "Student",
      },
      {
        time: "09:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "10:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "10:30",
        status: "booked",
        room: "Ruang 2.1",
        borrower: "Jane Smith",
        role: "Faculty",
      },
      {
        time: "11:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "11:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "12:00",
        status: "booked",
        room: "Ruang 2.1",
        borrower: "Alice Johnson",
        role: "Student",
      },
      {
        time: "12:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "13:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "13:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "14:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "14:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "15:00",
        status: "booked",
        room: "Ruang 2.1",
        borrower: "Mark Lee",
        role: "Staff",
      },
      {
        time: "15:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "16:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "16:30",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "17:00",
        status: "available",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "17:30",
        status: "holiday",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "18:00",
        status: "holiday",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
      {
        time: "18:30",
        status: "holiday",
        room: "Ruang 2.1",
        borrower: null,
        role: null,
      },
    ],
  };

  const ruang2_2 = {
    "2024-10-09": [
      {
        time: "08:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Michael Scott",
        role: "Manager",
      },
      {
        time: "08:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Dwight Schrute",
        role: "Assistant",
      },
      {
        time: "10:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "10:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "11:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Pam Beesly",
        role: "Receptionist",
      },
      {
        time: "11:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Jim Halpert",
        role: "Sales",
      },
      {
        time: "12:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "12:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Ryan Howard",
        role: "Temp",
      },
      {
        time: "13:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "13:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "14:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Toby Flenderson",
        role: "HR",
      },
      {
        time: "14:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Stanley Hudson",
        role: "Sales",
      },
      {
        time: "16:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "16:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Angela Martin",
        role: "Accounting",
      },
      {
        time: "17:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "null",
        role: "null",
      },
      {
        time: "17:30",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:00",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "23:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
    ],
  };

  const ruang3_1 = {
    "2024-10-09": [
      {
        time: "08:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Michael Scott",
        role: "Manager",
      },
      {
        time: "08:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Dwight Schrute",
        role: "Assistant",
      },
      {
        time: "10:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "10:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "11:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Pam Beesly",
        role: "Receptionist",
      },
      {
        time: "11:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Jim Halpert",
        role: "Sales",
      },
      {
        time: "12:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "12:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Ryan Howard",
        role: "Temp",
      },
      {
        time: "13:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "13:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "14:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Toby Flenderson",
        role: "HR",
      },
      {
        time: "14:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Stanley Hudson",
        role: "Sales",
      },
      {
        time: "16:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "16:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Angela Martin",
        role: "Accounting",
      },
      {
        time: "17:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "null",
        role: "null",
      },
      {
        time: "17:30",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:00",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:30",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
    ],
  };

  const ruang3_2 = {
    "2024-10-09": [
      {
        time: "08:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Michael Scott",
        role: "Manager",
      },
      {
        time: "08:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Dwight Schrute",
        role: "Assistant",
      },
      {
        time: "10:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "10:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "11:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Pam Beesly",
        role: "Receptionist",
      },
      {
        time: "11:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Jim Halpert",
        role: "Sales",
      },
      {
        time: "12:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "12:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Ryan Howard",
        role: "Temp",
      },
      {
        time: "13:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "13:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "14:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Toby Flenderson",
        role: "HR",
      },
      {
        time: "14:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Stanley Hudson",
        role: "Sales",
      },
      {
        time: "16:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "16:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Angela Martin",
        role: "Accounting",
      },
      {
        time: "17:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "null",
        role: "null",
      },
      {
        time: "17:30",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
    ],
  };

  const ruang4 = {
    "2024-10-10": [
      {
        time: "00:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: "Michael Scott",
        role: "Manager",
      },
      {
        time: "00:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:45",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:46",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:47",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:50",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:52",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:54",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "00:59",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "01:59",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "09:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Dwight Schrute",
        role: "Assistant",
      },
      {
        time: "10:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "10:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "11:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Pam Beesly",
        role: "Receptionist",
      },
      {
        time: "11:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Jim Halpert",
        role: "Sales",
      },
      {
        time: "12:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "12:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Ryan Howard",
        role: "Temp",
      },
      {
        time: "13:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "13:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "14:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Toby Flenderson",
        role: "HR",
      },
      {
        time: "14:30",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "15:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Stanley Hudson",
        role: "Sales",
      },
      {
        time: "16:00",
        status: "available",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "16:30",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "Angela Martin",
        role: "Accounting",
      },
      {
        time: "17:00",
        status: "booked",
        room: "Ruang 2.2",
        borrower: "null",
        role: "null",
      },
      {
        time: "17:30",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "18:00",
        status: "holiday",
        room: "Ruang 2.2",
        borrower: null,
        role: null,
      },
      {
        time: "23:52",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
      {
        time: "23:53",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
      {
        time: "23:55",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
      {
        time: "23:57",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
      {
        time: "23:58",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
      {
        time: "23:59",
        status: "available",
        room: "Ruang 4",
        borrower: null,
        role: null,
      },
    ],
  };

  return { ruang2_1, ruang2_2, ruang3_1, ruang3_2, ruang4 };
};
